### PR TITLE
Overhaul Catalyst's unit validation system

### LINKED ISSUE #1037: non-SI units not working
SI units works:
```julia
    @test_nowarn @reaction_network begin
        @ivs t [unit=u"s"]
        @species begin
            X1(t), [unit=u"mol/m^3"]
            Z1(t), [unit=u"mol/m^3"]
            X2(t), [unit=u"mol/m^3"]
            Z2(t), [unit=u"mol/m^3"]
            X3(t), [unit=u"mol/m^3"]
            Y3(t), [unit=u"mol/m^3"]
            Z3(t), [unit=u"mol/m^3"]
        end
        @parameters begin
            k1, [unit=u"(m^6)/(s*mol^2)"]
            v2, [unit=u"(m^6)/(s*mol^2)"]
            K2, [unit=u"mol/m^3"]
            v3, [unit=u"(m^3)/(s*mol)"]
            K3, [unit=u"mol/m^3"]
            n3
        end
        k1*X1, 2X1 --> Z1
        mm(X2, v2, K2), 3X2 --> Z2
        hill(X3, v3, K3, n3), X3 + Y3--> Z3
    end
```
passed, but non-SI units still have issues right now:
```julia
    @test_nowarn @reaction_network begin
        @ivs t [unit=u"s"]
        @species begin
            X1(t), [unit=u"μM"]
            Z1(t), [unit=u"μM"]
            X2(t), [unit=u"μM"]
            Z2(t), [unit=u"μM"]
            X3(t), [unit=u"μM"]
            Y3(t), [unit=u"μM"]
            Z3(t), [unit=u"μM"]
        end
        @parameters begin
            k1, [unit=u"1/(s*(μM)^2)"]
            v2, [unit=u"1/(s*(μM)^2)"]
            K2, [unit=u"μM"]
            v3, [unit=u"1/(s*μM)"]
            K3, [unit=u"μM"]
            n3
        end
        k1*X1, 2X1 --> Z1
        mm(X2, v2, K2), 3X2 --> Z2
        hill(X3, v3, K3, n3), X3 + Y3--> Z3
    end
```
gives
```julia
┌ Warning: Reaction rate laws are expected to have units of 0.0009999999999999998 m⁻³ s⁻¹ mol however, k1*X1(t), 2*X1 --> Z1 has units of 9.999999999999995e-7 m⁻³ s⁻¹ mol.
└ @ Catalyst ~/.julia/dev/Catalyst/src/reactionsystem.jl:1492
┌ Warning: Reaction rate laws are expected to have units of 0.0009999999999999998 m⁻³ s⁻¹ mol however, Catalyst.mm(X2(t), v2, K2), 3*X2 --> Z2 has units of 9.999999999999992e-10 m⁻³ s⁻¹ mol.
└ @ Catalyst ~/.julia/dev/Catalyst/src/reactionsystem.jl:1492
┌ Warning: Reaction rate laws are expected to have units of 0.0009999999999999998 m⁻³ s⁻¹ mol however, Catalyst.hill(X3(t), v3, K3, n3), X3 + Y3 --> Z3 has units of 9.999999999999995e-7 m⁻³ s⁻¹ mol.
└ @ Catalyst ~/.julia/dev/Catalyst/src/reactionsystem.jl:1492
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:903
  Expression: isempty(stderr_content)
   Evaluated: isempty("┌ Warning: Reaction rate laws are expected to have units of 0.0009999999999999998 m⁻³ s⁻¹ mol however, k1*X1(t), 2*X1 --> Z1 has units of 9.999999999999995e-7 m⁻³ s⁻¹ mol.\n└ @ Catalyst ~/.julia/dev/Catalyst/src/reactionsystem.jl:1492\n┌ Warning: Reaction rate laws are expected to have units of 0.0009999999999999998 m⁻³ s⁻¹ mol however, Catalyst.mm(X2(t), v2, K2), 3*X2 --> Z2 has units of 9.999999999999992e-10 m⁻³ s⁻¹ mol.\n└ @ Catalyst ~/.julia/dev/Catalyst/src/reactionsystem.jl:1492\n┌ Warning: Reaction rate laws are expected to have units of 0.0009999999999999998 m⁻³ s⁻¹ mol however, Catalyst.hill(X3(t), v3, K3, n3), X3 + Y3 --> Z3 has units of 9.999999999999995e-7 m⁻³ s⁻¹ mol.\n└ @ Catalyst ~/.julia/dev/Catalyst/src/reactionsystem.jl:1492\n")

ERROR: There was an error during testing
```
So it seems there are still issues with unit conversion to SI going on.

### PR DESCRIPTION
**Pull request by isaacsas**
Closes #1037

### Summary

- Replace Catalyst's unit validation with a new `catalyst_get_unit` implementation that preserves `SymbolicDimensions` (exact rational arithmetic) instead of expanding to concrete SI `Dimensions` (floating-point coefficients)
- Fix `validate` to correctly handle `only_use_rate=true` reactions and non-reaction equations (ODEs with noise terms)
- Remove the unused `Unitful` dependency
- Comprehensive test overhaul 

### Motivation

Catalyst's unit validation previously delegated to MTKBase's `get_unit`, which internally calls `uexpand` to convert all units to concrete SI dimensions. This uses floating-point exponent arithmetic, which introduces precision loss for non-SI units. For example, comparing `μM/s` against itself could fail because the molar mass conversion factor accumulated floating-point error in the dimension exponents.

This PR introduces `catalyst_get_unit`, which reads the raw `VariableUnit` metadata and performs arithmetic directly in `SymbolicDimensions` space (exact rational exponents). This is the same `SymbolicDimensions` type that users get when they write `us"μM"` — we just preserve it through the computation rather than expanding it.

We still use `DynamicQuantities` and the same `VariableUnit` metadata that MTKBase reads — we just avoid the `uexpand` step that loses precision for non-SI units.

### Changes

**New: `src/unit_helpers.jl`**
- `catalyst_get_unit(x, noise_units=nothing)` — SymbolicDimensions-preserving unit inference
- Handles all symbolic expression types: variables, calls, products, powers, additions, differentials, indexed arrays, registered functions (mm, hill, etc.)
- `_validate_unit_expr` / `_validate_equation` — additive-term consistency and equation LHS/RHS matching
- `_build_noise_units(rs)` — computes effective units for brownian (`time^(-1/2)`) and poissonian (rate parameter units) noise variables

**Modified: `src/reactionsystem.jl`**
- `validate(rs::ReactionSystem)` rewritten to use `catalyst_get_unit`
- Now correctly skips substrate unit multiplication for `only_use_rate=true` reactions
- Now validates non-reaction equations (brownian/poissonian noise, coupled ODEs)
- `validate` is now Catalyst's own function (not extending MTKBase's stub)

**Modified: `src/reaction.jl`**
- `validate(rx::Reaction)` rewritten to use `catalyst_get_unit`

**Modified: `src/Catalyst.jl`**
- Added `using DynamicQuantities` and `include("unit_helpers.jl")`
- Removed `import ModelingToolkitBase: validate` (Catalyst now owns `validate`)

**Modified: `Project.toml`**
- Removed `Unitful` from dependencies (was unused)

**Tests: `test/miscellaneous_tests/units.jl`** (rewritten, ~730 lines)
- `catalyst_get_unit` on primitives, expressions, differentials, higher-order derivatives
- Programmatic and DSL-based reaction system validation (M, μM, mixed units)
- `only_use_rate` reactions, compound rates, registered functions (mm, hill, hillr, hillar, mmr)
- Stochastic chemical kinetics (unitless species), functional parameters, brownians, poissonians
- Array variables with units, model conversions (ODE/SDE/Jump/NonlinearProblem)
- Equation unit validation (single ODEs, coupled systems, mixed reactions+equations)
- Bad unit detection (mismatched LHS/RHS, inconsistent additive terms)
- Conditional expressions (`ifelse`), higher-order derivatives

### CODE REVIEW

**Comment by isaacsas** [comment]
@TorkelE I need to give this a thorough read from start to finish, but if I don't see any issues I'll plan to merge. Might be a day or so as this one is long.

File: test/dsl/dsl_options.jl [hunk 1]
```diff
@@ -1629,6 +1629,33 @@ let
...
+    @test_throws Exception @eval @reaction_network begin
+        @checks true false
+        d, 3X --> 0
+    end
+    @test_throws Exception @eval @reaction_network begin
+        @checks 1
+        d, 3X --> 0
+    end
+end
+
```
Comment (TorkelE) [inline test/dsl/dsl_options.jl:1658]: These tests feel fairly underwhelming, should probably have a case with actual units (where it should and should not work) and test that.
(as a side note, I feel the AI seems to write tests with fairly strightforward models, but I think we have noticed that quite often errors are due to unitended consequences of combining different options, something we might want to keep in mind going forward)

**Comment by TorkelE** [comment]
I had a cursory read and looks good to merge if/when you are happy with it

File: test/dsl/dsl_options.jl (hunk 1 above)
Comment (isaacsas) [reply test/dsl/dsl_options.jl:1658]: Yes, I noticed that too but am taking break on this one. I plan to improve these before merging.

Comment (isaacsas) [reply test/dsl/dsl_options.jl:1658]: The simple system issue is true, but at the same time we have so much functionality it is tough to test every combination.

What we really need are some more comprehensive models that use *everything* we support, and for which we know the answers (or have hand-coded versions in the lower-level libraries), and a separate CI test for correctness. Those would be the ideal stress test that everything is coming together, but they need to be their own script/run because such models are likely to be very computationally expensive to run to adequate resolution to compare (since they will involve stochastic components).

Anyways, I've expanded these tests now.
